Repository kzi-nastava/ma-project-event-planner-siit-2024-team-23, pull requests merged in 2024-12, with the labels that each got.

#34 [merge] event type management #2.1.1
  app/src/main/java/com/example/fusmobilni/adapters/EventTypeAdapter.java
  app/src/main/java/com/example/fusmobilni/fragments/EventTypeFragments/EventTypeCard.java
  app/src/main/java/com/example/fusmobilni/fragments/EventTypeFragments/EventTypeCreationForm.java
  app/src/main/java/com/example/fusmobilni/fragments/EventTypeFragments/EventTypeFragment.java
  app/src/main/java/com/example/fusmobilni/interfaces/EventTypeListener.java
  app/src/main/java/com/example/fusmobilni/model/EventType.java
  app/src/main/java/com/example/fusmobilni/viewModels/EventTypeViewModel.java
  app/src/main/res/layout/fragment_event_type.xml
  app/src/main/res/layout/fragment_event_type_card.xml
  app/src/main/res/layout/fragment_event_type_creation_form.xml
  app/src/main/res/menu/nav_menu_admin.xml
  app/src/main/res/navigation/unauth_user_nav.xml
  app/src/main/res/values/strings.xml
Labels: feature

#35 Feature/event management #2.2.1
  app/src/main/java/com/example/fusmobilni/adapters/AgendaActivityAdapter.java
  app/src/main/java/com/example/fusmobilni/adapters/AgendaActivityEditableAdapter.java
  app/src/main/java/com/example/fusmobilni/adapters/BudgetPlaningItemAdapter.java
  app/src/main/java/com/example/fusmobilni/adapters/CreateEventAdapter.java
  app/src/main/java/com/example/fusmobilni/adapters/EventOrganizerEventAdapter.java
  app/src/main/java/com/example/fusmobilni/adapters/EventSelectionSpinnerAdapter.java
  app/src/main/java/com/example/fusmobilni/core/calendar/DayBinder.java
  app/src/main/java/com/example/fusmobilni/fragments/EventFragments/CreateEventFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/EventFragments/CreateEventSteps/ChooseProductFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/EventFragments/CreateEventSteps/CreateEventStepOne.java
  app/src/main/java/com/example/fusmobilni/fragments/EventFragments/CreateEventSteps/CreateEventStepThree.java
  app/src/main/java/com/example/fusmobilni/fragments/EventFragments/CreateEventSteps/CreateEventStepTwo.java
  app/src/main/java/com/example/fusmobilni/fragments/EventFragments/CreateEventSteps/InvitationsFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/EventFragments/EOEventCardHorizontal.java
  app/src/main/java/com/example/fusmobilni/fragments/EventFragments/EventDetailsFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/EventFragments/EventOrganizerEventFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/EventFragments/ItemEventActivity.java
  app/src/main/java/com/example/fusmobilni/fragments/EventSearchFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/HomeFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/ProductDetailsFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/ServiceReservationFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/UserProfileFragments/UserCalendarFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/UserProfileFragments/UserFavEventsFragment.java
  app/src/main/java/com/example/fusmobilni/interfaces/EOEventClickListener.java
  app/src/main/java/com/example/fusmobilni/interfaces/OnCategoryClickListener.java
  app/src/main/java/com/example/fusmobilni/model/AgendaActivity.java
  app/src/main/java/com/example/fusmobilni/model/Event.java
  app/src/main/java/com/example/fusmobilni/model/EventType.java
  app/src/main/java/com/example/fusmobilni/viewModels/EventViewModel.java
  app/src/main/res/drawable/rounded_shape.xml
  app/src/main/res/layout/dropdown_item.xml
  app/src/main/res/layout/fragment_choose_product.xml
  app/src/main/res/layout/fragment_create_agenda_activity.xml
  app/src/main/res/layout/fragment_create_event.xml
  app/src/main/res/layout/fragment_create_event_step_one.xml
  app/src/main/res/layout/fragment_create_event_step_three.xml
  app/src/main/res/layout/fragment_create_event_step_two.xml
  app/src/main/res/layout/fragment_e_o_event_card_horizontal.xml
  app/src/main/res/layout/fragment_event_details.xml
  app/src/main/res/layout/fragment_event_organizer_event_details.xml
  app/src/main/res/layout/fragment_event_type_card.xml
  app/src/main/res/layout/fragment_invitations.xml
  app/src/main/res/layout/fragment_item_activity_editable.xml
  app/src/main/res/layout/fragment_item_event_activity.xml
  app/src/main/res/layout/item_event_type_category.xml
  app/src/main/res/menu/nav_menu_event_organizer.xml
  app/src/main/res/navigation/unauth_user_nav.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: feature

#36 [merge] service form fix
  app/src/main/java/com/example/fusmobilni/fragments/MultiStepServiceFormOne.java
  app/src/main/java/com/example/fusmobilni/viewModels/ServiceViewModel.java
  app/src/main/res/layout/fragment_multi_step_service_form_one.xml
  app/src/main/res/values/strings.xml
Labels: feature

#38 [merge] Top 5 events on mobile working with backend
  app/build.gradle
  app/src/main/java/com/example/fusmobilni/adapters/events/event/EventsAdapter.java
  app/src/main/java/com/example/fusmobilni/adapters/events/event/EventsHorizontalAdapter.java
  app/src/main/java/com/example/fusmobilni/adapters/events/eventType/EventTypeFilterAdapter.java
  app/src/main/java/com/example/fusmobilni/adapters/items/product/ProductsAdapter.java
  app/src/main/java/com/example/fusmobilni/adapters/items/service/ServicesAdapter.java
  app/src/main/java/com/example/fusmobilni/clients/ClientUtils.java
  app/src/main/java/com/example/fusmobilni/clients/services/categories/CategoryService.java
  app/src/main/java/com/example/fusmobilni/clients/services/events/EventsService.java
  app/src/main/java/com/example/fusmobilni/clients/services/products/ProductsService.java
  app/src/main/java/com/example/fusmobilni/clients/services/serviceOfferings/ServiceOfferingService.java
  app/src/main/java/com/example/fusmobilni/fragments/HomeFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/events/event/filters/EventFilterFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/events/event/filters/EventSearchFragment.java
  app/src/main/java/com/example/fusmobilni/responses/events/EventTypeResponse.java
  app/src/main/java/com/example/fusmobilni/responses/events/EventTypesResponse.java
  app/src/main/java/com/example/fusmobilni/responses/events/filter/EventLocationsResponse.java
  app/src/main/java/com/example/fusmobilni/responses/events/filter/EventPaginationResponse.java
  app/src/main/java/com/example/fusmobilni/responses/events/filter/EventsPaginationResponse.java
  app/src/main/java/com/example/fusmobilni/responses/events/home/EventHomeResponse.java
  app/src/main/java/com/example/fusmobilni/responses/events/home/EventsHomeResponse.java
  app/src/main/java/com/example/fusmobilni/responses/items/CategoryResponse.java
  app/src/main/java/com/example/fusmobilni/responses/items/products/ProductHomeResponse.java
  app/src/main/java/com/example/fusmobilni/responses/items/products/ProductsHomeResponse.java
  app/src/main/java/com/example/fusmobilni/responses/items/services/ServiceHomeResponse.java
  app/src/main/java/com/example/fusmobilni/responses/items/services/ServicesHomeResponse.java
  app/src/main/java/com/example/fusmobilni/responses/location/LocationResponse.java
  app/src/main/java/com/example/fusmobilni/viewModels/events/filters/EventSearchViewModel.java
  app/src/main/res/drawable/category.xml
  app/src/main/res/drawable/category_inactive.xml
  app/src/main/res/layout/event_card.xml
  app/src/main/res/layout/event_fragment_search.xml
  app/src/main/res/layout/event_type_filter_card.xml
  app/src/main/res/layout/products_card.xml
  app/src/main/res/layout/service_card.xml
Labels: feature

#39 [merge] pagination, filtering and search for services woking with back end
  app/src/main/java/com/example/fusmobilni/adapters/events/event/EventsAdapter.java
  app/src/main/java/com/example/fusmobilni/adapters/events/event/EventsHorizontalAdapter.java
  app/src/main/java/com/example/fusmobilni/adapters/items/category/CategoryResponsesFilterAdapter.java
  app/src/main/java/com/example/fusmobilni/adapters/items/product/ProductsAdapter.java
  app/src/main/java/com/example/fusmobilni/adapters/items/service/ServiceHorizontalAdapter.java
  app/src/main/java/com/example/fusmobilni/adapters/items/service/ServicesAdapter.java
  app/src/main/java/com/example/fusmobilni/clients/ClientUtils.java
  app/src/main/java/com/example/fusmobilni/clients/services/products/ProductsService.java
  app/src/main/java/com/example/fusmobilni/clients/services/serviceOfferings/ServiceOfferingService.java
  app/src/main/java/com/example/fusmobilni/fragments/HomeFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/events/event/createEventSteps/ChooseProductFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/events/event/filters/EventSearchFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/items/service/Filters/ServiceFragmentFilter.java
  app/src/main/java/com/example/fusmobilni/fragments/items/service/Filters/ServiceSearchFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/users/profile/UserFavItemsFragment.java
  app/src/main/java/com/example/fusmobilni/responses/items/CategoriesResponse.java
  app/src/main/java/com/example/fusmobilni/responses/items/CategoryResponse.java
  app/src/main/java/com/example/fusmobilni/responses/items/products/filter/ProductLocationsResponse.java
  app/src/main/java/com/example/fusmobilni/responses/items/products/filter/ProductPaginationResponse.java
  app/src/main/java/com/example/fusmobilni/responses/items/products/filter/ProductsPaginationResponse.java
  app/src/main/java/com/example/fusmobilni/responses/items/products/home/ProductHomeResponse.java
  app/src/main/java/com/example/fusmobilni/responses/items/products/home/ProductsHomeResponse.java
  app/src/main/java/com/example/fusmobilni/responses/items/services/filter/ServiceLocationsResponse.java
  app/src/main/java/com/example/fusmobilni/responses/items/services/filter/ServicePaginationResponse.java
  app/src/main/java/com/example/fusmobilni/responses/items/services/filter/ServicesMinMaxPriceResponse.java
  app/src/main/java/com/example/fusmobilni/responses/items/services/filter/ServicesPaginationResponse.java
  app/src/main/java/com/example/fusmobilni/responses/items/services/home/ServiceHomeResponse.java
  app/src/main/java/com/example/fusmobilni/responses/items/services/home/ServicesHomeResponse.java
  app/src/main/java/com/example/fusmobilni/viewModels/events/filters/EventSearchViewModel.java
  app/src/main/java/com/example/fusmobilni/viewModels/items/service/filters/ServiceSearchViewModel.java
  app/src/main/res/layout/event_card_horizontal.xml
  app/src/main/res/layout/fragment_service_details.xml
  app/src/main/res/layout/fragment_service_filter.xml
  app/src/main/res/layout/fragment_service_search.xml
  app/src/main/res/layout/service_card.xml
  app/src/main/res/layout/service_card_horizontal.xml
Labels: feature

#40 [merge] search, pagination and filtering working with back end
  app/src/main/java/com/example/fusmobilni/adapters/items/product/ProductsResponseAdapter.java
  app/src/main/java/com/example/fusmobilni/clients/services/products/ProductsService.java
  app/src/main/java/com/example/fusmobilni/fragments/items/product/filters/ProductFilterFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/items/product/filters/ProductSearchFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/items/service/Filters/ServiceSearchFragment.java
  app/src/main/java/com/example/fusmobilni/responses/items/products/filter/ProductPaginationResponse.java
  app/src/main/java/com/example/fusmobilni/responses/items/products/filter/ProductsMinMaxPriceResponse.java
  app/src/main/java/com/example/fusmobilni/viewModels/events/filters/EventSearchViewModel.java
  app/src/main/java/com/example/fusmobilni/viewModels/items/product/filters/ProductSearchViewModel.java
  app/src/main/java/com/example/fusmobilni/viewModels/items/service/filters/ServiceSearchViewModel.java
  app/src/main/res/layout/fragment_product_search.xml
  app/src/main/res/layout/product_card_horizontal.xml
Labels: feature

#41 [merge] event invitations sync with back end
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/fusmobilni/activities/FastRegisterActivity.java
  app/src/main/java/com/example/fusmobilni/clients/ClientUtils.java
  app/src/main/java/com/example/fusmobilni/clients/services/events/inivtations/InvitationsService.java
  app/src/main/java/com/example/fusmobilni/clients/services/fastRegister/FastRegisterService.java
  app/src/main/java/com/example/fusmobilni/fragments/events/event/createEventSteps/InvitationsFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/users/register/fast/HashInvalidFragment.java
  app/src/main/java/com/example/fusmobilni/requests/events/invitations/InvitationCreateRequest.java
  app/src/main/java/com/example/fusmobilni/requests/events/invitations/InvitationsCreateRequest.java
  app/src/main/java/com/example/fusmobilni/requests/register/fast/FastRegisterRequest.java
  app/src/main/java/com/example/fusmobilni/responses/FastRegisterInvitationResponse.java
  app/src/main/java/com/example/fusmobilni/responses/events/invitations/InvitationResponse.java
  app/src/main/java/com/example/fusmobilni/responses/events/invitations/InvitationsResponse.java
  app/src/main/java/com/example/fusmobilni/viewModels/events/event/InvitationsViewModel.java
  app/src/main/res/layout/fragment_hash_invalid.xml
  app/src/main/res/layout/fragment_invitations.xml
  app/src/main/res/layout/fragment_step_two_fast_registration.xml
Labels: feature

#43 [merge] Service reservation sync with back end into develop
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/fusmobilni/activities/FastRegisterActivity.java
  app/src/main/java/com/example/fusmobilni/adapters/items/service/ServiceHorizontalAdapter.java
  app/src/main/java/com/example/fusmobilni/adapters/items/service/ServicesAdapter.java
  app/src/main/java/com/example/fusmobilni/clients/ClientUtils.java
  app/src/main/java/com/example/fusmobilni/clients/services/serviceOfferings/ServiceOfferingReservationService.java
  app/src/main/java/com/example/fusmobilni/clients/services/serviceOfferings/ServiceOfferingService.java
  app/src/main/java/com/example/fusmobilni/fragments/items/service/ServiceDetailsFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/items/service/ServiceReservationFragment.java
  app/src/main/java/com/example/fusmobilni/responses/auth/EventOrganizerResponse.java
  app/src/main/java/com/example/fusmobilni/responses/auth/ServiceProviderResponse.java
  app/src/main/java/com/example/fusmobilni/responses/items/ItemGradeResponse.java
  app/src/main/java/com/example/fusmobilni/responses/items/services/ServiceOverviewResponse.java
  app/src/main/java/com/example/fusmobilni/responses/items/services/ServiceReservationResponse.java
  app/src/main/res/layout/fragment_service_details.xml
  app/src/main/res/layout/fragment_service_reservation.xml
  app/src/main/res/navigation/unauth_user_nav.xml
Labels: feature

#45 [merge] redesigned cards and loading cards into develop
  app/build.gradle
  app/src/main/java/com/example/fusmobilni/adapters/events/event/EventsHorizontalAdapter.java
  app/src/main/java/com/example/fusmobilni/adapters/loading/LoadingCardHorizontalAdapter.java
  app/src/main/java/com/example/fusmobilni/adapters/loading/LoadingCardVerticalAdapter.java
  app/src/main/java/com/example/fusmobilni/fragments/HomeFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/events/event/filters/EventFilterFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/events/event/filters/EventSearchFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/items/product/filters/ProductFilterFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/items/product/filters/ProductSearchFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/items/service/Filters/ServiceFragmentFilter.java
  app/src/main/java/com/example/fusmobilni/fragments/items/service/Filters/ServiceSearchFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/loading/LoadingCardHorizontalFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/loading/LoadingCardVerticalFragment.java
  app/src/main/java/com/example/fusmobilni/viewModels/events/filters/EventSearchViewModel.java
  app/src/main/java/com/example/fusmobilni/viewModels/items/product/filters/ProductSearchViewModel.java
  app/src/main/java/com/example/fusmobilni/viewModels/items/service/filters/ServiceSearchViewModel.java
  app/src/main/res/layout/event_card_horizontal.xml
  app/src/main/res/layout/event_fragment_search.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_loading_card_horizontal.xml
  app/src/main/res/layout/fragment_loading_card_vertical.xml
  app/src/main/res/layout/fragment_product_search.xml
  app/src/main/res/layout/fragment_service_search.xml
  app/src/main/res/layout/product_card_horizontal.xml
  app/src/main/res/layout/service_card_horizontal.xml
  app/src/main/res/values/colors.xml
Labels: redesign

#46 [merge] event budget planning
  app/build.gradle
  app/src/main/java/com/example/fusmobilni/adapters/events/AgendaActivityEditableAdapter.java
  app/src/main/java/com/example/fusmobilni/adapters/events/eventType/EventTypeAdapter.java
  app/src/main/java/com/example/fusmobilni/adapters/events/eventType/EventTypeFilterAdapter.java
  app/src/main/java/com/example/fusmobilni/adapters/items/BudgetPlaningItemAdapter.java
  app/src/main/java/com/example/fusmobilni/adapters/items/ItemsHorizontalAdapter.java
  app/src/main/java/com/example/fusmobilni/clients/ClientUtils.java
  app/src/main/java/com/example/fusmobilni/clients/services/eventTypes/EventTypeService.java
  app/src/main/java/com/example/fusmobilni/clients/services/events/EventsService.java
  app/src/main/java/com/example/fusmobilni/clients/services/items/ItemsService.java
  app/src/main/java/com/example/fusmobilni/fragments/events/event/CreateEventFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/events/event/EventDetailsFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/events/event/createEventSteps/ChooseProductFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/events/event/createEventSteps/CreateEventStepOne.java
  app/src/main/java/com/example/fusmobilni/fragments/events/event/createEventSteps/CreateEventStepThree.java
  app/src/main/java/com/example/fusmobilni/fragments/events/event/createEventSteps/CreateEventStepTwo.java
  app/src/main/java/com/example/fusmobilni/fragments/events/eventType/EventTypeCreationForm.java
  app/src/main/java/com/example/fusmobilni/fragments/events/eventType/EventTypeFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/items/product/ProductDetailsFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/items/service/ServiceDetailsFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/items/service/ServiceReservationFragment.java
  app/src/main/java/com/example/fusmobilni/interfaces/OnCategoryClickListener.java
  app/src/main/java/com/example/fusmobilni/model/event/AgendaActivity.java
  app/src/main/java/com/example/fusmobilni/model/event/eventTypes/EventType.java
  app/src/main/java/com/example/fusmobilni/model/event/eventTypes/SuggestedCategories.java
  app/src/main/java/com/example/fusmobilni/model/items/category/OfferingsCategory.java
  app/src/main/java/com/example/fusmobilni/model/items/item/ItemDetails.java
  app/src/main/java/com/example/fusmobilni/model/users/ServiceProviderDetails.java
  app/src/main/java/com/example/fusmobilni/requests/events/event/AgendaActivitiesResponse.java
  app/src/main/java/com/example/fusmobilni/requests/events/event/CreateAgendaActivityRequest.java
  app/src/main/java/com/example/fusmobilni/requests/events/event/CreateEventRequest.java
  app/src/main/java/com/example/fusmobilni/requests/events/event/EventComponentReservationRequest.java
  app/src/main/java/com/example/fusmobilni/requests/events/event/GetItemsByCategoryAndPrice.java
  app/src/main/java/com/example/fusmobilni/requests/items/BuyItemRequest.java
  app/src/main/java/com/example/fusmobilni/responses/events/EventTypesResponse.java
  app/src/main/java/com/example/fusmobilni/responses/events/GetEventByIdResponse.java
  app/src/main/java/com/example/fusmobilni/responses/events/GetEventResponse.java
  app/src/main/java/com/example/fusmobilni/responses/events/GetEventTypeWithCategoriesResponse.java
  app/src/main/java/com/example/fusmobilni/responses/events/GetEventTypesWithCategoriesResponse.java
  app/src/main/java/com/example/fusmobilni/responses/events/GetItemResponse.java
  app/src/main/java/com/example/fusmobilni/responses/events/GetItemsResponse.java
  app/src/main/java/com/example/fusmobilni/responses/events/components/AgendaActivityResponse.java
  app/src/main/java/com/example/fusmobilni/responses/events/components/EventComponentResponse.java
  app/src/main/java/com/example/fusmobilni/responses/events/components/EventComponentsResponse.java
  app/src/main/java/com/example/fusmobilni/viewModels/events/event/EventViewModel.java
  app/src/main/java/com/example/fusmobilni/viewModels/events/eventTypes/EventTypeViewModel.java
  app/src/main/res/layout/fragment_choose_product.xml
  app/src/main/res/layout/fragment_create_event_step_one.xml
  app/src/main/res/layout/product_card_horizontal.xml
  app/src/main/res/navigation/unauth_user_nav.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/network_security_config.xml
Labels: feature

#47 [merge]
  app/src/main/java/com/example/fusmobilni/fragments/items/category/CategoryCreationForm.java
  app/src/main/java/com/example/fusmobilni/fragments/items/category/proposals/ModifyCategoryProposalFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/items/service/Forms/MultiStepServiceFormOne.java
  app/src/main/java/com/example/fusmobilni/fragments/items/service/Forms/MultiStepServiceFormThree.java
  app/src/main/java/com/example/fusmobilni/fragments/items/service/Forms/MultiStepServiceFormTwo.java
  app/src/main/java/com/example/fusmobilni/viewModels/items/service/ServiceViewModel.java
  app/src/main/java/com/example/fusmobilni/viewModels/users/serviceProvider/ServiceProviderViewModel.java
  app/src/main/res/layout/fragment_multi_step_service_form_three.xml
  app/src/main/res/values/strings.xml
Labels: fix

#49 [merge] fixed validation on service reservation page
  app/src/main/java/com/example/fusmobilni/fragments/events/event/createEventSteps/CreateEventStepTwo.java
  app/src/main/java/com/example/fusmobilni/fragments/events/event/createEventSteps/InvitationsFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/items/service/ServiceReservationFragment.java
Labels: fix

#51 Feature/interceptor client utils
  app/src/main/java/com/example/fusmobilni/activities/FastRegisterActivity.java
  app/src/main/java/com/example/fusmobilni/activities/HomeActivity.java
  app/src/main/java/com/example/fusmobilni/activities/LoginActivity.java
  app/src/main/java/com/example/fusmobilni/activities/RegisterActivity.java
  app/src/main/java/com/example/fusmobilni/activities/SplashScreenActivity.java
  app/src/main/java/com/example/fusmobilni/activities/VerifyEmailActivity.java
  app/src/main/java/com/example/fusmobilni/clients/AuthInterceptor.java
  app/src/main/java/com/example/fusmobilni/clients/ClientUtils.java
  app/src/main/java/com/example/fusmobilni/core/CustomSharedPrefs.java
  app/src/main/java/com/example/fusmobilni/fragments/events/event/createEventSteps/InvitationsFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/users/profile/UpdateProfileFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/users/profile/ViewProfileFragment.java
  app/src/main/java/com/example/fusmobilni/viewModels/users/login/LoginViewModel.java
Labels: feature

#52 [merge] item grading modal into develop
  app/src/main/java/com/example/fusmobilni/adapters/items/reviews/ItemReviewFormAdapter.java
  app/src/main/java/com/example/fusmobilni/adapters/items/reviews/ItemReviewsAdapter.java
  app/src/main/java/com/example/fusmobilni/clients/services/items/ItemsService.java
  app/src/main/java/com/example/fusmobilni/fragments/items/reviews/ItemReviewFormFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/items/reviews/ItemReviewFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/items/service/ServiceDetailsFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/items/service/ServiceDetailsRegularFragment.java
  app/src/main/java/com/example/fusmobilni/requests/items/ItemReviewCreateRequest.java
  app/src/main/java/com/example/fusmobilni/responses/auth/ServiceProviderDetailsResponse.java
  app/src/main/java/com/example/fusmobilni/responses/items/EventOrganizerReviewResponse.java
  app/src/main/java/com/example/fusmobilni/responses/items/IsBoughtItemResponse.java
  app/src/main/java/com/example/fusmobilni/responses/items/ItemGradeResponse.java
  app/src/main/java/com/example/fusmobilni/responses/items/services/ServiceOverviewResponse.java
  app/src/main/res/drawable/fill_star_24.xml
  app/src/main/res/drawable/ic_star.xml
  app/src/main/res/drawable/ic_star_fill.xml
  app/src/main/res/layout/event_card_horizontal.xml
  app/src/main/res/layout/fragment_item_review.xml
  app/src/main/res/layout/fragment_item_review_form.xml
  app/src/main/res/layout/fragment_service_details.xml
  app/src/main/res/layout/fragment_service_details_regular.xml
  app/src/main/res/layout/item_review_form_stars.xml
  app/src/main/res/navigation/unauth_user_nav.xml
  app/src/main/res/xml/network_security_config.xml
Labels: feature

#53 [merge] user register #1.1.5
  app/src/main/java/com/example/fusmobilni/activities/RegisterActivity.java
  app/src/main/java/com/example/fusmobilni/clients/auth/AuthService.java
  app/src/main/java/com/example/fusmobilni/fragments/users/register/regular/StepOneFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/users/register/regular/StepThreeFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/users/register/regular/StepTwoFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/users/register/regular/VerifyEmailFragment.java
  app/src/main/java/com/example/fusmobilni/interfaces/ILocationCallback.java
  app/src/main/java/com/example/fusmobilni/interfaces/IRegisterCallback.java
  app/src/main/java/com/example/fusmobilni/requests/register/regular/RegisterRequest.java
  app/src/main/java/com/example/fusmobilni/responses/register/regular/RegisterResponse.java
  app/src/main/java/com/example/fusmobilni/viewModels/users/register/RegisterViewModel.java
  app/src/main/res/layout/fragment_step_two.xml
  app/src/main/res/values/strings.xml
Labels: feature

#56 [merge] pricelist overview
  app/src/main/java/com/example/fusmobilni/adapters/items/pricelist/PriceListAdapter.java
  app/src/main/java/com/example/fusmobilni/clients/ClientUtils.java
  app/src/main/java/com/example/fusmobilni/clients/services/items/pricelist/PriceListService.java
  app/src/main/java/com/example/fusmobilni/fragments/items/pricelist/EditPriceListItemFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/items/pricelist/PriceListFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/items/service/Forms/MultiStepServiceFormOne.java
  app/src/main/java/com/example/fusmobilni/fragments/items/service/ServiceDetailsRegularFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/items/service/ServiceView.java
  app/src/main/java/com/example/fusmobilni/interfaces/PriceListListener.java
  app/src/main/java/com/example/fusmobilni/requests/items/pricelist/PriceListUpdateRequest.java
  app/src/main/java/com/example/fusmobilni/responses/items/pricelist/PriceListGetResponse.java
  app/src/main/java/com/example/fusmobilni/responses/items/pricelist/PriceListsGetResponse.java
  app/src/main/java/com/example/fusmobilni/viewModels/items/pricelist/PriceListViewModel.java
  app/src/main/java/com/example/fusmobilni/viewModels/items/service/ServiceViewModel.java
  app/src/main/res/layout/fragment_edit_price_list_item.xml
  app/src/main/res/layout/fragment_price_list.xml
  app/src/main/res/layout/price_list_item.xml
  app/src/main/res/menu/nav_menu_service_provider.xml
  app/src/main/res/navigation/unauth_user_nav.xml
  app/src/main/res/values/strings.xml
Labels: feature

#57 [merge] Event type management #2.6.5
  app/src/main/java/com/example/fusmobilni/adapters/events/event/EventsAdapter.java
  app/src/main/java/com/example/fusmobilni/adapters/events/eventType/EventTypeAdapter.java
  app/src/main/java/com/example/fusmobilni/adapters/items/product/ProductsAdapter.java
  app/src/main/java/com/example/fusmobilni/adapters/items/product/ProductsHorizontalAdapter.java
  app/src/main/java/com/example/fusmobilni/adapters/items/service/ServicesAdapter.java
  app/src/main/java/com/example/fusmobilni/adapters/users/ViewProfileEventAdapter.java
  app/src/main/java/com/example/fusmobilni/clients/ClientUtils.java
  app/src/main/java/com/example/fusmobilni/clients/services/eventTypes/EventTypeService.java
  app/src/main/java/com/example/fusmobilni/clients/users/UserService.java
  app/src/main/java/com/example/fusmobilni/core/calendar/DayBinder.java
  app/src/main/java/com/example/fusmobilni/fragments/HomeFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/events/eventType/EventTypeCreationForm.java
  app/src/main/java/com/example/fusmobilni/fragments/events/eventType/EventTypeFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/users/profile/AboutUserFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/users/profile/StepOneUpdateFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/users/profile/UpdateProfileFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/users/profile/UserCalendarFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/users/profile/UserFavEventsFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/users/profile/UserFavItemsFragment.java
  app/src/main/java/com/example/fusmobilni/interfaces/ICalendarCallback.java
  app/src/main/java/com/example/fusmobilni/interfaces/IEventTypeCallback.java
  app/src/main/java/com/example/fusmobilni/interfaces/IUpdateProfileCallback.java
  app/src/main/java/com/example/fusmobilni/model/enums/UserType.java
  app/src/main/java/com/example/fusmobilni/model/event/eventTypes/EventType.java
  app/src/main/java/com/example/fusmobilni/model/event/eventTypes/EventTypeStatus.java
  app/src/main/java/com/example/fusmobilni/requests/eventTypes/EventTypeCreateRequest.java
  app/src/main/java/com/example/fusmobilni/requests/eventTypes/EventTypeUpdateRequest.java
  app/src/main/java/com/example/fusmobilni/requests/users/AuthenticatedUserUpdateRequest.java
  app/src/main/java/com/example/fusmobilni/requests/users/ServiceProviderUpdateRequest.java
  app/src/main/java/com/example/fusmobilni/requests/users/favorites/FavoriteEventRequest.java
  app/src/main/java/com/example/fusmobilni/requests/users/favorites/FavoriteProductRequest.java
  app/src/main/java/com/example/fusmobilni/requests/users/favorites/FavoriteServiceRequest.java
  app/src/main/java/com/example/fusmobilni/responses/users/UserFavoriteEventResponse.java
  app/src/main/java/com/example/fusmobilni/responses/users/UserFavoriteEventsResponse.java
  app/src/main/java/com/example/fusmobilni/responses/users/UserFavoriteProductResponse.java
  app/src/main/java/com/example/fusmobilni/responses/users/UserFavoriteProductsResponse.java
  app/src/main/java/com/example/fusmobilni/responses/users/UserFavoriteServiceResponse.java
  app/src/main/java/com/example/fusmobilni/responses/users/UserFavoriteServicesResponse.java
  app/src/main/java/com/example/fusmobilni/responses/users/UserInfoPreviewResponse.java
  app/src/main/java/com/example/fusmobilni/responses/users/UserInfoResponse.java
  app/src/main/java/com/example/fusmobilni/viewModels/events/eventTypes/EventTypeViewModel.java
  app/src/main/java/com/example/fusmobilni/viewModels/users/UpdateProfileViewModel.java
  app/src/main/res/layout/event_card_horizontal.xml
  app/src/main/res/layout/fragment_about_user.xml
  app/src/main/res/layout/fragment_step_one_update.xml
  app/src/main/res/layout/fragment_update_profile.xml
  app/src/main/res/layout/fragment_user_events_fragments.xml
  app/src/main/res/layout/fragment_user_items_fragment.xml
  app/src/main/res/navigation/unauth_user_nav.xml
  app/src/main/res/values/strings.xml
Labels: feature

#59 Feature/chat #4.1.2
  app/build.gradle
  app/src/main/java/com/example/fusmobilni/adapters/communication/chats/ChatAdapter.java
  app/src/main/java/com/example/fusmobilni/adapters/communication/chats/ChatsOverviewAdapter.java
  app/src/main/java/com/example/fusmobilni/clients/ClientUtils.java
  app/src/main/java/com/example/fusmobilni/clients/services/communication/chat/ChatService.java
  app/src/main/java/com/example/fusmobilni/clients/webSockets/WebSocketClient.java
  app/src/main/java/com/example/fusmobilni/fragments/communication/MessagesFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/communication/chat/ChatFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/communication/chat/ChatsOverviewFragment.java
  app/src/main/java/com/example/fusmobilni/helper/UriConverter.java
  app/src/main/java/com/example/fusmobilni/interfaces/ChatListener.java
  app/src/main/java/com/example/fusmobilni/model/communication/chat/ChatOverview.java
  app/src/main/java/com/example/fusmobilni/requests/communication/chat/ChatCreateRequest.java
  app/src/main/java/com/example/fusmobilni/requests/communication/chat/MessageCreateRequest.java
  app/src/main/java/com/example/fusmobilni/responses/communication/chat/ChatGetResponse.java
  app/src/main/java/com/example/fusmobilni/responses/communication/chat/ChatsGetResponse.java
  app/src/main/java/com/example/fusmobilni/responses/communication/chat/UserChatResponse.java
  app/src/main/java/com/example/fusmobilni/responses/communication/chat/messages/GetMessageResponse.java
  app/src/main/java/com/example/fusmobilni/responses/communication/chat/messages/GetMessagesResponse.java
  app/src/main/java/com/example/fusmobilni/viewModels/communication/chat/ChatViewModel.java
  app/src/main/res/drawable/circle_background.xml
  app/src/main/res/drawable/rounded_button_background.xml
  app/src/main/res/drawable/rounded_edit_text_background.xml
  app/src/main/res/layout/chat_message.xml
  app/src/main/res/layout/chat_overview_card.xml
  app/src/main/res/layout/fragment_chat.xml
  app/src/main/res/layout/fragment_chats_overview.xml
  app/src/main/res/layout/fragment_messages.xml
  app/src/main/res/menu/nav_menu_auth_user.xml
  app/src/main/res/menu/nav_menu_event_organizer.xml
  app/src/main/res/menu/nav_menu_service_provider.xml
  app/src/main/res/menu/toolbar_menu.xml
  app/src/main/res/navigation/unauth_user_nav.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: feature

#61 [merge] redesigned notification logic into develop
  app/src/main/java/com/example/fusmobilni/activities/HomeActivity.java
  app/src/main/java/com/example/fusmobilni/clients/webSockets/ChatWebSocketClient.java
  app/src/main/java/com/example/fusmobilni/clients/webSockets/NotificationWebSocketClient.java
  app/src/main/java/com/example/fusmobilni/fragments/communication/NotificationsFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/communication/chat/ChatFragment.java
  app/src/main/java/com/example/fusmobilni/viewModels/notifications/NotificationViewModel.java
Labels: redesign

#62 [merge] Event details #2.9.5
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/fusmobilni/adapters/events/AgendaActivityAdapter.java
  app/src/main/java/com/example/fusmobilni/adapters/events/EventComponentAdapter.java
  app/src/main/java/com/example/fusmobilni/adapters/events/event/EventsAdapter.java
  app/src/main/java/com/example/fusmobilni/adapters/events/event/EventsHorizontalAdapter.java
  app/src/main/java/com/example/fusmobilni/adapters/items/product/ProductsAdapter.java
  app/src/main/java/com/example/fusmobilni/adapters/items/service/ServicesAdapter.java
  app/src/main/java/com/example/fusmobilni/adapters/users/eventOrganizer/EventOrganizerEventAdapter.java
  app/src/main/java/com/example/fusmobilni/clients/ClientUtils.java
  app/src/main/java/com/example/fusmobilni/clients/services/auth/AuthService.java
  app/src/main/java/com/example/fusmobilni/clients/services/events/EventsService.java
  app/src/main/java/com/example/fusmobilni/clients/services/users/UserService.java
  app/src/main/java/com/example/fusmobilni/clients/users/UserService.java
  app/src/main/java/com/example/fusmobilni/fragments/events/event/EventDetailsFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/events/event/EventOrganizerEventFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/users/profile/ViewProfileFragment.java
  app/src/main/java/com/example/fusmobilni/responses/events/EventDetailsResponse.java
  app/src/main/java/com/example/fusmobilni/responses/events/home/EventPreviewResponse.java
  app/src/main/java/com/example/fusmobilni/responses/events/home/EventsPreviewResponse.java
  app/src/main/java/com/example/fusmobilni/responses/location/LocationResponse.java
  app/src/main/java/com/example/fusmobilni/viewModels/notifications/NotificationViewModel.java
  app/src/main/res/drawable/event_image_placeholder.jpg
  app/src/main/res/drawable/img.png
  app/src/main/res/layout/event_card.xml
  app/src/main/res/layout/fragment_event_component.xml
  app/src/main/res/layout/fragment_event_details.xml
  app/src/main/res/layout/fragment_event_organizer_event_details.xml
  app/src/main/res/navigation/unauth_user_nav.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/provider_paths.xml
Labels: feature

#63 [merge] pricelist export into pdf
  app/build.gradle
  app/src/main/java/com/example/fusmobilni/adapters/users/eventOrganizer/EventOrganizerEventAdapter.java
  app/src/main/java/com/example/fusmobilni/clients/services/items/pricelist/PriceListService.java
  app/src/main/java/com/example/fusmobilni/fragments/communication/chat/ChatFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/events/event/EventDetailsFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/events/event/createEventSteps/CreateEventStepThree.java
  app/src/main/java/com/example/fusmobilni/fragments/items/company/CompanyOverviewFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/items/pricelist/PriceListFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/items/product/ProductDetailsFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/items/service/ServiceDetailsFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/items/service/ServiceDetailsRegularFragment.java
  app/src/main/java/com/example/fusmobilni/responses/users/GetCompanyOverviewResponse.java
  app/src/main/res/layout/fragment_company_overview.xml
  app/src/main/res/layout/fragment_e_o_event_card_horizontal.xml
  app/src/main/res/layout/fragment_event_details.xml
  app/src/main/res/layout/fragment_price_list.xml
  app/src/main/res/navigation/unauth_user_nav.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/network_security_config.xml
  gradle/libs.versions.toml
Labels: feature

#65 [merge] Product #3.22.2
  app/src/main/java/com/example/fusmobilni/adapters/users/serviceProvider/ServiceProviderProductAdapter.java
  app/src/main/java/com/example/fusmobilni/clients/services/products/ProductsService.java
  app/src/main/java/com/example/fusmobilni/fragments/items/product/Forms/MultiStepProductFormOne.java
  app/src/main/java/com/example/fusmobilni/fragments/items/product/Forms/MultiStepProductFormThree.java
  app/src/main/java/com/example/fusmobilni/fragments/items/product/Forms/MultiStepProductFormTwo.java
  app/src/main/java/com/example/fusmobilni/fragments/items/product/ProductsFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/items/product/filters/ProductFilterFragment.java
  app/src/main/java/com/example/fusmobilni/requests/products/CreateProductProposalRequest.java
  app/src/main/java/com/example/fusmobilni/requests/products/CreateProductRequest.java
  app/src/main/java/com/example/fusmobilni/requests/products/GetProductResponse.java
  app/src/main/java/com/example/fusmobilni/requests/products/GetProductsResponse.java
  app/src/main/java/com/example/fusmobilni/requests/products/UpdateProductRequest.java
  app/src/main/java/com/example/fusmobilni/viewModels/items/product/ProductViewModel.java
  app/src/main/java/com/example/fusmobilni/viewModels/items/product/filters/ProductSearchViewModel.java
  app/src/main/java/com/example/fusmobilni/viewModels/users/serviceProvider/ServiceProviderViewModel.java
  app/src/main/res/layout/fragment_delete_service_modal.xml
  app/src/main/res/layout/fragment_products.xml
  app/src/main/res/layout/product_card_horizontal_sp.xml
  app/src/main/res/navigation/unauth_user_nav.xml
  app/src/main/res/values/strings.xml
Labels: feature

#67 [merge] Product/service details fragment with add to favorites functionality
  app/src/main/java/com/example/fusmobilni/adapters/items/product/ProductsAdapter.java
  app/src/main/java/com/example/fusmobilni/clients/services/products/ProductsService.java
  app/src/main/java/com/example/fusmobilni/fragments/items/product/ProductsFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/items/service/ServiceDetailsRegularFragment.java
  app/src/main/java/com/example/fusmobilni/interfaces/item/BaseItem.java
  app/src/main/java/com/example/fusmobilni/interfaces/item/ServiceOffering.java
  app/src/main/java/com/example/fusmobilni/responses/items/products/ProductOverviewResponse.java
Labels: feature

#68 [merge] event changes notifications
  app/src/main/java/com/example/fusmobilni/adapters/communication/notifications/NotificationsAdapter.java
  app/src/main/java/com/example/fusmobilni/fragments/communication/notifications/NotificationsFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/notifications/EventUpdateNotificationFragment.java
  app/src/main/java/com/example/fusmobilni/fragments/notifications/EventUpdateNotificationUnreadFragment.java
  app/src/main/res/layout/fragment_event_update_notification.xml
  app/src/main/res/layout/fragment_event_update_notification_unread.xml
Labels: feature
